### ISSUE TITLE
Hugo-TOC startet bei Level 2

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/kitest#81]
Das von Hugo generierte TOC startet bei H2. Das passt normalerweise, aber bei `lecture-bc` fehlen dann die H1-Überschriften. 

`config.yaml`:

```yaml
markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
```
